# Generated by Django 6.0 on 2026-01-02 23:46

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=17, unique=True, validators=[books.models.validate_isbn], verbose_name='ISBN')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El costo debe ser mayor a 0.')], verbose_name='Costo USD')),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de venta local')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('supplier_country', models.CharField(help_text='Código ISO de 2 letras (ej: ES, US, MX)', max_length=2, verbose_name='País del proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'books',
                'ordering': ['-created_at'],
            },
        ),
    ]
